import crypto from 'crypto';

export interface SeedQuestion {
    difficulty: number;
    prompt: string;
    choices: string[];
    correctAnswer: string;
    correctAnswerHash: string;
    tags: string[];
}

function hashAnswer(answer: string): string {
    return crypto.createHash('sha256').update(answer.trim().toLowerCase()).digest('hex');
}

export const seedQuestions: SeedQuestion[] = [
    // ===== DIFFICULTY 1 (Beginner) =====
    { difficulty: 1, prompt: "What is the capital of France?", choices: ["London", "Berlin", "Paris", "Madrid"], correctAnswer: "Paris", correctAnswerHash: hashAnswer("Paris"), tags: ["geography"] },
    { difficulty: 1, prompt: "How many legs does a spider have?", choices: ["6", "8", "10", "4"], correctAnswer: "8", correctAnswerHash: hashAnswer("8"), tags: ["science"] },
    { difficulty: 1, prompt: "What color is the sky on a clear day?", choices: ["Green", "Blue", "Red", "Yellow"], correctAnswer: "Blue", correctAnswerHash: hashAnswer("Blue"), tags: ["general"] },
    { difficulty: 1, prompt: "What is 2 + 2?", choices: ["3", "4", "5", "6"], correctAnswer: "4", correctAnswerHash: hashAnswer("4"), tags: ["math"] },
    { difficulty: 1, prompt: "Which animal is known as man's best friend?", choices: ["Cat", "Dog", "Fish", "Bird"], correctAnswer: "Dog", correctAnswerHash: hashAnswer("Dog"), tags: ["general"] },
    { difficulty: 1, prompt: "How many days are in a week?", choices: ["5", "6", "7", "8"], correctAnswer: "7", correctAnswerHash: hashAnswer("7"), tags: ["general"] },
    { difficulty: 1, prompt: "What planet do we live on?", choices: ["Mars", "Venus", "Earth", "Jupiter"], correctAnswer: "Earth", correctAnswerHash: hashAnswer("Earth"), tags: ["science"] },
    { difficulty: 1, prompt: "What is the largest ocean on Earth?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], correctAnswer: "Pacific", correctAnswerHash: hashAnswer("Pacific"), tags: ["geography"] },
    { difficulty: 1, prompt: "Which fruit is yellow and curved?", choices: ["Apple", "Banana", "Orange", "Grape"], correctAnswer: "Banana", correctAnswerHash: hashAnswer("Banana"), tags: ["general"] },
    { difficulty: 1, prompt: "How many months are in a year?", choices: ["10", "11", "12", "13"], correctAnswer: "12", correctAnswerHash: hashAnswer("12"), tags: ["general"] },

    // ===== DIFFICULTY 2 =====
    { difficulty: 2, prompt: "Which gas do plants absorb from the atmosphere?", choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctAnswer: "Carbon Dioxide", correctAnswerHash: hashAnswer("Carbon Dioxide"), tags: ["science"] },
    { difficulty: 2, prompt: "What is the largest continent?", choices: ["Africa", "Asia", "Europe", "North America"], correctAnswer: "Asia", correctAnswerHash: hashAnswer("Asia"), tags: ["geography"] },
    { difficulty: 2, prompt: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], correctAnswer: "6", correctAnswerHash: hashAnswer("6"), tags: ["math"] },
    { difficulty: 2, prompt: "What is the chemical symbol for water?", choices: ["H2O", "CO2", "O2", "NaCl"], correctAnswer: "H2O", correctAnswerHash: hashAnswer("H2O"), tags: ["science"] },
    { difficulty: 2, prompt: "Which country is known as the Land of the Rising Sun?", choices: ["China", "Japan", "Korea", "Thailand"], correctAnswer: "Japan", correctAnswerHash: hashAnswer("Japan"), tags: ["geography"] },
    { difficulty: 2, prompt: "What is the square root of 64?", choices: ["6", "7", "8", "9"], correctAnswer: "8", correctAnswerHash: hashAnswer("8"), tags: ["math"] },
    { difficulty: 2, prompt: "Who wrote 'Romeo and Juliet'?", choices: ["Dickens", "Shakespeare", "Austen", "Twain"], correctAnswer: "Shakespeare", correctAnswerHash: hashAnswer("Shakespeare"), tags: ["literature"] },
    { difficulty: 2, prompt: "What is the boiling point of water in Celsius?", choices: ["90°C", "100°C", "110°C", "120°C"], correctAnswer: "100°C", correctAnswerHash: hashAnswer("100°C"), tags: ["science"] },
    { difficulty: 2, prompt: "Which instrument has 88 keys?", choices: ["Guitar", "Violin", "Piano", "Drums"], correctAnswer: "Piano", correctAnswerHash: hashAnswer("Piano"), tags: ["music"] },
    { difficulty: 2, prompt: "How many bones are in the human body?", choices: ["106", "206", "306", "406"], correctAnswer: "206", correctAnswerHash: hashAnswer("206"), tags: ["science"] },

    // ===== DIFFICULTY 3 =====
    { difficulty: 3, prompt: "What is the chemical symbol for gold?", choices: ["Go", "Gd", "Au", "Ag"], correctAnswer: "Au", correctAnswerHash: hashAnswer("Au"), tags: ["science"] },
    { difficulty: 3, prompt: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Jupiter", "Saturn"], correctAnswer: "Mars", correctAnswerHash: hashAnswer("Mars"), tags: ["science"] },
    { difficulty: 3, prompt: "In which year did World War II end?", choices: ["1943", "1944", "1945", "1946"], correctAnswer: "1945", correctAnswerHash: hashAnswer("1945"), tags: ["history"] },
    { difficulty: 3, prompt: "What is the largest mammal?", choices: ["Elephant", "Blue Whale", "Giraffe", "Hippo"], correctAnswer: "Blue Whale", correctAnswerHash: hashAnswer("Blue Whale"), tags: ["science"] },
    { difficulty: 3, prompt: "Which programming language is known for web development?", choices: ["C++", "JavaScript", "Fortran", "Assembly"], correctAnswer: "JavaScript", correctAnswerHash: hashAnswer("JavaScript"), tags: ["technology"] },
    { difficulty: 3, prompt: "What is the currency of Japan?", choices: ["Yuan", "Won", "Yen", "Ringgit"], correctAnswer: "Yen", correctAnswerHash: hashAnswer("Yen"), tags: ["geography"] },
    { difficulty: 3, prompt: "How many continents are there?", choices: ["5", "6", "7", "8"], correctAnswer: "7", correctAnswerHash: hashAnswer("7"), tags: ["geography"] },
    { difficulty: 3, prompt: "What does CPU stand for?", choices: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], correctAnswer: "Central Processing Unit", correctAnswerHash: hashAnswer("Central Processing Unit"), tags: ["technology"] },
    { difficulty: 3, prompt: "Who painted the Mona Lisa?", choices: ["Van Gogh", "Picasso", "Da Vinci", "Monet"], correctAnswer: "Da Vinci", correctAnswerHash: hashAnswer("Da Vinci"), tags: ["art"] },
    { difficulty: 3, prompt: "What is the speed of light approximately?", choices: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], correctAnswer: "300,000 km/s", correctAnswerHash: hashAnswer("300,000 km/s"), tags: ["science"] },

    // ===== DIFFICULTY 4 =====
    { difficulty: 4, prompt: "What is the Pythagorean theorem?", choices: ["a² + b² = c²", "a + b = c", "a² × b² = c²", "a² - b² = c²"], correctAnswer: "a² + b² = c²", correctAnswerHash: hashAnswer("a² + b² = c²"), tags: ["math"] },
    { difficulty: 4, prompt: "Which element has the atomic number 1?", choices: ["Helium", "Hydrogen", "Lithium", "Carbon"], correctAnswer: "Hydrogen", correctAnswerHash: hashAnswer("Hydrogen"), tags: ["science"] },
    { difficulty: 4, prompt: "What is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctAnswer: "Nile", correctAnswerHash: hashAnswer("Nile"), tags: ["geography"] },
    { difficulty: 4, prompt: "In which year was the Internet invented?", choices: ["1969", "1975", "1983", "1991"], correctAnswer: "1969", correctAnswerHash: hashAnswer("1969"), tags: ["technology"] },
    { difficulty: 4, prompt: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], correctAnswer: "2", correctAnswerHash: hashAnswer("2"), tags: ["math"] },
    { difficulty: 4, prompt: "Which vitamin is produced when skin is exposed to sunlight?", choices: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctAnswer: "Vitamin D", correctAnswerHash: hashAnswer("Vitamin D"), tags: ["science"] },
    { difficulty: 4, prompt: "What is the capital of Australia?", choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correctAnswer: "Canberra", correctAnswerHash: hashAnswer("Canberra"), tags: ["geography"] },
    { difficulty: 4, prompt: "Who developed the theory of general relativity?", choices: ["Newton", "Einstein", "Hawking", "Bohr"], correctAnswer: "Einstein", correctAnswerHash: hashAnswer("Einstein"), tags: ["science"] },
    { difficulty: 4, prompt: "What is the binary representation of the number 10?", choices: ["1010", "1100", "1001", "0110"], correctAnswer: "1010", correctAnswerHash: hashAnswer("1010"), tags: ["technology"] },
    { difficulty: 4, prompt: "Which organ in the human body produces insulin?", choices: ["Liver", "Kidney", "Pancreas", "Stomach"], correctAnswer: "Pancreas", correctAnswerHash: hashAnswer("Pancreas"), tags: ["science"] },

    // ===== DIFFICULTY 5 =====
    { difficulty: 5, prompt: "What is the time complexity of binary search?", choices: ["O(n)", "O(log n)", "O(n²)", "O(1)"], correctAnswer: "O(log n)", correctAnswerHash: hashAnswer("O(log n)"), tags: ["technology"] },
    { difficulty: 5, prompt: "Which treaty ended World War I?", choices: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Vienna", "Treaty of Ghent"], correctAnswer: "Treaty of Versailles", correctAnswerHash: hashAnswer("Treaty of Versailles"), tags: ["history"] },
    { difficulty: 5, prompt: "What is the chemical formula for sulfuric acid?", choices: ["HCl", "H2SO4", "HNO3", "H3PO4"], correctAnswer: "H2SO4", correctAnswerHash: hashAnswer("H2SO4"), tags: ["science"] },
    { difficulty: 5, prompt: "In which data structure does LIFO principle apply?", choices: ["Queue", "Stack", "Array", "Tree"], correctAnswer: "Stack", correctAnswerHash: hashAnswer("Stack"), tags: ["technology"] },
    { difficulty: 5, prompt: "What is the derivative of x²?", choices: ["x", "2x", "x²", "2x²"], correctAnswer: "2x", correctAnswerHash: hashAnswer("2x"), tags: ["math"] },
    { difficulty: 5, prompt: "Which country has the most natural lakes?", choices: ["USA", "Russia", "Finland", "Canada"], correctAnswer: "Canada", correctAnswerHash: hashAnswer("Canada"), tags: ["geography"] },
    { difficulty: 5, prompt: "What does SQL stand for?", choices: ["Structured Query Language", "Simple Query Language", "Standard Query Logic", "Sequential Query Language"], correctAnswer: "Structured Query Language", correctAnswerHash: hashAnswer("Structured Query Language"), tags: ["technology"] },
    { difficulty: 5, prompt: "What is Avogadro's number approximately?", choices: ["6.022 × 10²³", "3.14 × 10⁸", "1.602 × 10⁻¹⁹", "9.81 × 10¹"], correctAnswer: "6.022 × 10²³", correctAnswerHash: hashAnswer("6.022 × 10²³"), tags: ["science"] },
    { difficulty: 5, prompt: "Who founded the Python programming language?", choices: ["Dennis Ritchie", "James Gosling", "Guido van Rossum", "Bjarne Stroustrup"], correctAnswer: "Guido van Rossum", correctAnswerHash: hashAnswer("Guido van Rossum"), tags: ["technology"] },
    { difficulty: 5, prompt: "What is the largest desert in the world?", choices: ["Sahara", "Arabian", "Gobi", "Antarctic"], correctAnswer: "Antarctic", correctAnswerHash: hashAnswer("Antarctic"), tags: ["geography"] },

    // ===== DIFFICULTY 6 =====
    { difficulty: 6, prompt: "What sorting algorithm has the best average-case time complexity?", choices: ["Bubble Sort", "Merge Sort", "Selection Sort", "Insertion Sort"], correctAnswer: "Merge Sort", correctAnswerHash: hashAnswer("Merge Sort"), tags: ["technology"] },
    { difficulty: 6, prompt: "What is the integral of 1/x?", choices: ["x", "ln|x| + C", "1/x² + C", "e^x + C"], correctAnswer: "ln|x| + C", correctAnswerHash: hashAnswer("ln|x| + C"), tags: ["math"] },
    { difficulty: 6, prompt: "Which protocol is used for secure web communication?", choices: ["HTTP", "FTP", "HTTPS", "SMTP"], correctAnswer: "HTTPS", correctAnswerHash: hashAnswer("HTTPS"), tags: ["technology"] },
    { difficulty: 6, prompt: "What is the powerhouse of the cell?", choices: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"], correctAnswer: "Mitochondria", correctAnswerHash: hashAnswer("Mitochondria"), tags: ["science"] },
    { difficulty: 6, prompt: "In graph theory, what algorithm finds shortest paths from a single source?", choices: ["Kruskal's", "Prim's", "Dijkstra's", "Floyd-Warshall"], correctAnswer: "Dijkstra's", correctAnswerHash: hashAnswer("Dijkstra's"), tags: ["technology"] },
    { difficulty: 6, prompt: "What is the half-life of Carbon-14 approximately?", choices: ["1,000 years", "2,730 years", "5,730 years", "10,000 years"], correctAnswer: "5,730 years", correctAnswerHash: hashAnswer("5,730 years"), tags: ["science"] },
    { difficulty: 6, prompt: "Which design pattern ensures only one instance of a class?", choices: ["Factory", "Observer", "Singleton", "Strategy"], correctAnswer: "Singleton", correctAnswerHash: hashAnswer("Singleton"), tags: ["technology"] },
    { difficulty: 6, prompt: "What is the nationality of the mathematician Euler?", choices: ["German", "French", "Swiss", "Dutch"], correctAnswer: "Swiss", correctAnswerHash: hashAnswer("Swiss"), tags: ["math"] },
    { difficulty: 6, prompt: "Which layer of the OSI model handles routing?", choices: ["Data Link", "Network", "Transport", "Session"], correctAnswer: "Network", correctAnswerHash: hashAnswer("Network"), tags: ["technology"] },
    { difficulty: 6, prompt: "What is the escape velocity from Earth?", choices: ["7.9 km/s", "11.2 km/s", "15.4 km/s", "3.2 km/s"], correctAnswer: "11.2 km/s", correctAnswerHash: hashAnswer("11.2 km/s"), tags: ["science"] },

    // ===== DIFFICULTY 7 =====
    { difficulty: 7, prompt: "What is the CAP theorem in distributed systems?", choices: ["Consistency, Availability, Partition tolerance", "Cache, API, Performance", "Concurrency, Atomicity, Persistence", "Capacity, Access, Protocol"], correctAnswer: "Consistency, Availability, Partition tolerance", correctAnswerHash: hashAnswer("Consistency, Availability, Partition tolerance"), tags: ["technology"] },
    { difficulty: 7, prompt: "What is the Heisenberg Uncertainty Principle about?", choices: ["Energy conservation", "Position and momentum cannot both be precisely known", "Speed of light is constant", "Matter can be created"], correctAnswer: "Position and momentum cannot both be precisely known", correctAnswerHash: hashAnswer("Position and momentum cannot both be precisely known"), tags: ["science"] },
    { difficulty: 7, prompt: "In Big-O notation, what is the complexity of the best comparison-based sorting algorithm?", choices: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], correctAnswer: "O(n log n)", correctAnswerHash: hashAnswer("O(n log n)"), tags: ["technology"] },
    { difficulty: 7, prompt: "What is the Riemann Hypothesis concerned with?", choices: ["Prime numbers", "Gravity", "Black holes", "Thermodynamics"], correctAnswer: "Prime numbers", correctAnswerHash: hashAnswer("Prime numbers"), tags: ["math"] },
    { difficulty: 7, prompt: "Which consensus algorithm does Bitcoin use?", choices: ["Proof of Stake", "Proof of Work", "Raft", "Paxos"], correctAnswer: "Proof of Work", correctAnswerHash: hashAnswer("Proof of Work"), tags: ["technology"] },
    { difficulty: 7, prompt: "What is the Chandrasekhar limit?", choices: ["Maximum mass of a white dwarf", "Speed of light in vacuum", "Minimum mass of a black hole", "Temperature of the Sun's core"], correctAnswer: "Maximum mass of a white dwarf", correctAnswerHash: hashAnswer("Maximum mass of a white dwarf"), tags: ["science"] },
    { difficulty: 7, prompt: "What does ACID stand for in database transactions?", choices: ["Atomicity, Consistency, Isolation, Durability", "Access, Control, Integration, Data", "Automated, Concurrent, Indexed, Distributed", "Aligned, Computed, Isolated, Derived"], correctAnswer: "Atomicity, Consistency, Isolation, Durability", correctAnswerHash: hashAnswer("Atomicity, Consistency, Isolation, Durability"), tags: ["technology"] },
    { difficulty: 7, prompt: "Who proposed the theory of natural selection alongside Darwin?", choices: ["Lamarck", "Wallace", "Mendel", "Linnaeus"], correctAnswer: "Wallace", correctAnswerHash: hashAnswer("Wallace"), tags: ["science"] },
    { difficulty: 7, prompt: "What is a Bloom filter used for?", choices: ["Sorting data", "Probabilistic set membership testing", "Encrypting data", "Compressing files"], correctAnswer: "Probabilistic set membership testing", correctAnswerHash: hashAnswer("Probabilistic set membership testing"), tags: ["technology"] },
    { difficulty: 7, prompt: "What is the Taylor series expansion of e^x at x=0?", choices: ["1 + x + x²/2! + x³/3! + ...", "x + x²/2 + x³/3 + ...", "1 + x + x² + x³ + ...", "x - x³/3! + x⁵/5! - ..."], correctAnswer: "1 + x + x²/2! + x³/3! + ...", correctAnswerHash: hashAnswer("1 + x + x²/2! + x³/3! + ..."), tags: ["math"] },

    // ===== DIFFICULTY 8 =====
    { difficulty: 8, prompt: "What is the space complexity of Depth-First Search?", choices: ["O(V)", "O(V + E)", "O(V²)", "O(E)"], correctAnswer: "O(V)", correctAnswerHash: hashAnswer("O(V)"), tags: ["technology"] },
    { difficulty: 8, prompt: "In quantum computing, what is superposition?", choices: ["A qubit being in multiple states simultaneously", "Two qubits being entangled", "A quantum gate operation", "Error correction in quantum circuits"], correctAnswer: "A qubit being in multiple states simultaneously", correctAnswerHash: hashAnswer("A qubit being in multiple states simultaneously"), tags: ["science"] },
    { difficulty: 8, prompt: "What is the Kolmogorov complexity of a string?", choices: ["Length of the string", "Length of shortest program that produces it", "Number of unique characters", "Entropy of the string"], correctAnswer: "Length of shortest program that produces it", correctAnswerHash: hashAnswer("Length of shortest program that produces it"), tags: ["technology"] },
    { difficulty: 8, prompt: "What is the Euler characteristic of a torus?", choices: ["0", "1", "2", "-1"], correctAnswer: "0", correctAnswerHash: hashAnswer("0"), tags: ["math"] },
    { difficulty: 8, prompt: "Which algorithm is used for finding strongly connected components?", choices: ["BFS", "Tarjan's", "Binary Search", "A*"], correctAnswer: "Tarjan's", correctAnswerHash: hashAnswer("Tarjan's"), tags: ["technology"] },
    { difficulty: 8, prompt: "What is the Pauli Exclusion Principle?", choices: ["No two identical fermions can occupy the same quantum state", "Energy is conserved in all processes", "Every action has an equal reaction", "Light behaves as both wave and particle"], correctAnswer: "No two identical fermions can occupy the same quantum state", correctAnswerHash: hashAnswer("No two identical fermions can occupy the same quantum state"), tags: ["science"] },
    { difficulty: 8, prompt: "What is eventual consistency in distributed systems?", choices: ["All replicas are always consistent", "Given enough time without updates, all replicas converge", "Data is never consistent", "Only the primary is consistent"], correctAnswer: "Given enough time without updates, all replicas converge", correctAnswerHash: hashAnswer("Given enough time without updates, all replicas converge"), tags: ["technology"] },
    { difficulty: 8, prompt: "What is the Halting Problem?", choices: ["Determining if a program will finish", "Finding the shortest path", "Sorting in minimum time", "Optimizing memory usage"], correctAnswer: "Determining if a program will finish", correctAnswerHash: hashAnswer("Determining if a program will finish"), tags: ["technology"] },
    { difficulty: 8, prompt: "What is the Schrödinger equation used for?", choices: ["Describing quantum state evolution", "Calculating planetary orbits", "Modeling fluid dynamics", "Predicting chemical reactions"], correctAnswer: "Describing quantum state evolution", correctAnswerHash: hashAnswer("Describing quantum state evolution"), tags: ["science"] },
    { difficulty: 8, prompt: "What is the Church-Turing thesis?", choices: ["Any computable function can be computed by a Turing machine", "P = NP", "All algorithms terminate", "Quantum computers are more powerful"], correctAnswer: "Any computable function can be computed by a Turing machine", correctAnswerHash: hashAnswer("Any computable function can be computed by a Turing machine"), tags: ["technology"] },

    // ===== DIFFICULTY 9 =====
    { difficulty: 9, prompt: "What is the amortized time complexity of operations on a Fibonacci heap?", choices: ["O(1) for decrease-key", "O(log n) for decrease-key", "O(n) for decrease-key", "O(n log n) for decrease-key"], correctAnswer: "O(1) for decrease-key", correctAnswerHash: hashAnswer("O(1) for decrease-key"), tags: ["technology"] },
    { difficulty: 9, prompt: "What is the Bekenstein bound?", choices: ["Maximum entropy in a bounded region", "Minimum energy of a quantum system", "Maximum speed of information transfer", "Minimum size of a black hole"], correctAnswer: "Maximum entropy in a bounded region", correctAnswerHash: hashAnswer("Maximum entropy in a bounded region"), tags: ["science"] },
    { difficulty: 9, prompt: "In type theory, what is the Curry-Howard correspondence?", choices: ["Types correspond to propositions, programs to proofs", "Functions correspond to sets", "Variables correspond to constants", "Types correspond to data structures"], correctAnswer: "Types correspond to propositions, programs to proofs", correctAnswerHash: hashAnswer("Types correspond to propositions, programs to proofs"), tags: ["technology"] },
    { difficulty: 9, prompt: "What is the fastest known matrix multiplication algorithm's complexity?", choices: ["O(n³)", "O(n²·³⁷)", "O(n² log n)", "O(n²)"], correctAnswer: "O(n²·³⁷)", correctAnswerHash: hashAnswer("O(n²·³⁷)"), tags: ["math"] },
    { difficulty: 9, prompt: "What is a Merkle tree used for in distributed systems?", choices: ["Data encryption", "Efficient data verification and synchronization", "Load balancing", "Message queuing"], correctAnswer: "Efficient data verification and synchronization", correctAnswerHash: hashAnswer("Efficient data verification and synchronization"), tags: ["technology"] },
    { difficulty: 9, prompt: "What is the Poincaré conjecture about?", choices: ["Every simply connected 3-manifold is homeomorphic to a 3-sphere", "Prime numbers distribution", "Graph coloring", "Fluid dynamics"], correctAnswer: "Every simply connected 3-manifold is homeomorphic to a 3-sphere", correctAnswerHash: hashAnswer("Every simply connected 3-manifold is homeomorphic to a 3-sphere"), tags: ["math"] },
    { difficulty: 9, prompt: "What is the Byzantine Generals Problem?", choices: ["Achieving consensus with potentially faulty nodes", "Optimizing network routing", "Balancing load across servers", "Encrypting communications"], correctAnswer: "Achieving consensus with potentially faulty nodes", correctAnswerHash: hashAnswer("Achieving consensus with potentially faulty nodes"), tags: ["technology"] },
    { difficulty: 9, prompt: "What is renormalization in quantum field theory?", choices: ["Removing infinities from calculations", "Normalizing wavefunctions", "Renaming variables", "Resetting initial conditions"], correctAnswer: "Removing infinities from calculations", correctAnswerHash: hashAnswer("Removing infinities from calculations"), tags: ["science"] },
    { difficulty: 9, prompt: "What is the Raft consensus algorithm designed for?", choices: ["Replicated state machines", "Sorting distributed data", "Load balancing", "Data encryption"], correctAnswer: "Replicated state machines", correctAnswerHash: hashAnswer("Replicated state machines"), tags: ["technology"] },
    { difficulty: 9, prompt: "What is Gödel's incompleteness theorem about?", choices: ["No consistent system can prove all truths about arithmetic", "All mathematical statements can be proven", "Mathematics is complete", "Logic is always consistent"], correctAnswer: "No consistent system can prove all truths about arithmetic", correctAnswerHash: hashAnswer("No consistent system can prove all truths about arithmetic"), tags: ["math"] },

    // ===== DIFFICULTY 10 (Expert) =====
    { difficulty: 10, prompt: "What is the complexity class BQP?", choices: ["Bounded-error Quantum Polynomial time", "Binary Quantum Processing", "Boolean Query Protocol", "Balanced Queue Priority"], correctAnswer: "Bounded-error Quantum Polynomial time", correctAnswerHash: hashAnswer("Bounded-error Quantum Polynomial time"), tags: ["technology"] },
    { difficulty: 10, prompt: "What is the AdS/CFT correspondence?", choices: ["A duality between gravity in anti-de Sitter space and conformal field theory", "A relationship between algorithms and data structures", "A quantum computing paradigm", "A network protocol"], correctAnswer: "A duality between gravity in anti-de Sitter space and conformal field theory", correctAnswerHash: hashAnswer("A duality between gravity in anti-de Sitter space and conformal field theory"), tags: ["science"] },
    { difficulty: 10, prompt: "What is the significance of P vs NP problem?", choices: ["Whether every problem verifiable in polynomial time is also solvable in polynomial time", "Whether parallel computing is faster", "Whether quantum computers can break encryption", "Whether AI can think"], correctAnswer: "Whether every problem verifiable in polynomial time is also solvable in polynomial time", correctAnswerHash: hashAnswer("Whether every problem verifiable in polynomial time is also solvable in polynomial time"), tags: ["technology"] },
    { difficulty: 10, prompt: "What is a Calabi-Yau manifold?", choices: ["A compact complex manifold with vanishing first Chern class", "A type of graph structure", "A sorting algorithm", "A quantum computing architecture"], correctAnswer: "A compact complex manifold with vanishing first Chern class", correctAnswerHash: hashAnswer("A compact complex manifold with vanishing first Chern class"), tags: ["math"] },
    { difficulty: 10, prompt: "What is the Langlands program?", choices: ["A network of conjectures connecting number theory and geometry", "A software development methodology", "A space exploration initiative", "A quantum computing framework"], correctAnswer: "A network of conjectures connecting number theory and geometry", correctAnswerHash: hashAnswer("A network of conjectures connecting number theory and geometry"), tags: ["math"] },
    { difficulty: 10, prompt: "What is topological quantum computing based on?", choices: ["Anyons and braiding operations", "Classical bit manipulation", "Photon entanglement only", "Superconducting circuits only"], correctAnswer: "Anyons and braiding operations", correctAnswerHash: hashAnswer("Anyons and braiding operations"), tags: ["technology"] },
    { difficulty: 10, prompt: "What is the holographic principle in theoretical physics?", choices: ["The information in a volume of space can be described by a theory on its boundary", "Holograms can store quantum data", "Light behaves as particles", "The universe is a simulation"], correctAnswer: "The information in a volume of space can be described by a theory on its boundary", correctAnswerHash: hashAnswer("The information in a volume of space can be described by a theory on its boundary"), tags: ["science"] },
    { difficulty: 10, prompt: "What is the Erdős–Rényi model?", choices: ["A random graph model", "A sorting algorithm", "A database indexing strategy", "A network routing protocol"], correctAnswer: "A random graph model", correctAnswerHash: hashAnswer("A random graph model"), tags: ["math"] },
    { difficulty: 10, prompt: "In distributed computing, what does the FLP impossibility result state?", choices: ["No deterministic consensus protocol can guarantee progress in an asynchronous system with even one crash failure", "All distributed systems can reach consensus", "Byzantine faults are always detectable", "Network partitions cannot occur"], correctAnswer: "No deterministic consensus protocol can guarantee progress in an asynchronous system with even one crash failure", correctAnswerHash: hashAnswer("No deterministic consensus protocol can guarantee progress in an asynchronous system with even one crash failure"), tags: ["technology"] },
    { difficulty: 10, prompt: "What is the Yang-Mills mass gap problem?", choices: ["Proving that quantum Yang-Mills theory exists and has a mass gap", "Finding the mass of a photon", "Calculating nuclear binding energy", "Measuring gravitational waves"], correctAnswer: "Proving that quantum Yang-Mills theory exists and has a mass gap", correctAnswerHash: hashAnswer("Proving that quantum Yang-Mills theory exists and has a mass gap"), tags: ["science"] },
];
